name: Vet

on:  
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema.yaml
          target: endpoints
